# Generated by Django 4.0.2 on 2022-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=15)),
                ('details', models.TextField(max_length=1000)),
                ('pub_date', models.TimeField(auto_now_add=True)),
                ('mod_date', models.TimeField(auto_now=True)),
                ('link', models.URLField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NeedHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=15)),
                ('details', models.TextField(max_length=1000)),
                ('pub_date', models.TimeField(auto_now_add=True)),
                ('mod_date', models.TimeField(auto_now=True)),
                ('link', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
