# Generated by Django 4.0 on 2022-02-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_help_address_needhelp_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='valabil',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='needhelp',
            name='valabil',
            field=models.BooleanField(default=True),
        ),
    ]
