# Generated by Django 4.0 on 2022-02-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_help_valabil_needhelp_valabil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='address',
            field=models.CharField(choices=[('chisinau', 'chisinau'), ('balti', 'balti'), ('comrat', 'comrat'), ('anenii_noi', 'anenii_noi'), ('basarabeasca', 'basarabeasca'), ('briceni', 'briceni'), ('cahul', 'cahul'), ('cantemir', 'cantemir'), ('calarasi', 'calarasi'), ('causeni', 'causeni'), ('cimislia', 'cimislia'), ('criuleni', 'criuleni'), ('donduseni', 'donduseni'), ('drochia', 'drochia'), ('dubasari', 'dubasari'), ('edinet', 'edinet'), ('falesti', 'falesti'), ('floresti', 'floresti'), ('glodeni', 'glodeni'), ('hincesti', 'hincesti'), ('ialoveni', 'ialoveni'), ('leova', 'leova'), ('nisporeni', 'nisporeni'), ('ocnita', 'ocnita'), ('orhei', 'orhei'), ('rezina', 'rezina'), ('riscani', 'riscani'), ('singerei', 'singerei'), ('soroca', 'soroca'), ('straseni', 'straseni'), ('soldanesti', 'soldanesti'), ('stefan_voda', 'stefan_voda'), ('taraclia', 'taraclia'), ('telenesti', 'telenesti'), ('ungheni', 'ungheni')], default='chisinau', max_length=1000),
        ),
    ]
