# Generated by Django 4.0 on 2022-02-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_help_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needhelp',
            name='address',
        ),
    ]
