# Generated by Django 4.0.2 on 2022-02-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_needhelp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='needhelp',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='needhelp',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
