# Generated by Django 4.0.2 on 2022-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_help_pub_date_help_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='needhelp',
            name='category',
            field=models.CharField(choices=[('cazare', 'Cazare | Проживання'), ('transport', 'Transport | Транспорт'), ('consiliere', 'Consiliere | Консультування'), ('voluntariat', 'Волонтерство, переклад'), ('donatii', 'Haine, alimente | Одяг, їжа'), ('lucru', 'Lucru | Работа ')], default='None', max_length=20, null=True),
        ),
    ]
