# Generated by Django 4.0 on 2022-02-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_needhelp_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needhelp',
            name='pub_date',
        ),
    ]
