# Generated by Django 4.0.2 on 2022-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_help_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='author',
            field=models.CharField(choices=[('fizica', 'Persoana Fizica | Физическое лицо'), ('juridica', 'Persoana Juridica | Юридическое лицо')], default='None', max_length=10, null=True),
        ),
    ]
